spring: 
 
  datasource:
    name: security_group_test
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/security_group_test?useUnicode=true&amp;characterEncoding=UTF8&amp;autoReconnect=true&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 8
      max-lifetime: 1800000
      maximum-pool-size: 15
      
#logging:
#  level:
#    org.springframework.security: DEBUG