spring:
  datasource:
    name: test
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 8
      max-lifetime: 1800000
      maximum-pool-size: 15

